### PR TITLE
GNNExplainer: apply opt only for a target label

### PR DESCRIPTION
**Pull request by alirezadizaji**
Hi,
I was running GNNExplainer optimization on GPU and realized that it's a bit slow due to getting edge masks for all existing labels.
I added an option to also support optimization only for a target label.

### CODE REVIEW

**Comment by CM-BF** [comment]
Thank you for the useful feature! I hope to include your contributions to our branch. But here are some issues before I can apply to merge.

- Due to the incompatibility of PyG, we have updated our code to support PyG 2.0.x. The main branch now is `dig-stable` instead of `dig`. It is better to update the PyG version to 2.x and pushes the modification to the `dig-stable` branch.
- In this pull request, you include not only the modification of GNNExplainer but also the PGExplainer's. This makes me hard to review and merge directly because the PGExplaienr is not maintained by me. If you can split them into two pull requests, I can incorporate your great contributions as soon as possible.

Thank you again for your contributions. Please contact me if any discussion. 😄

**Comment by alirezadizaji** [comment]
Sure about the first one, but are you sure about PGExplainer modification in this PR? Indeed, I had dropped unrelated commits and "Files Changed" tab also shows only one file modification

**Comment by alirezadizaji** [comment]
Shall I close this and open a new pull request because I changed target branch in edit part and it brought some other files

**Comment by CM-BF** [comment]
You are right. I was carelessly confused by the checkpoint comparison. And, yes, please reopen a new pull request.

**Pull request closed without merging**
