### PR TITLE
Graph augmentation

### PR DESCRIPTION
**Pull request by anmol-anand**
The GraphAug model has three parts:
(1) Reward Generator: A GNN model that rewards label invariant augmentations.
(2) Generator: A model that can generate label invariant graph augmentations.
(3) Testing: Testing improvement in classification accuracy after using the augmented dataset.

### CODE REVIEW

**Review by lyzustc — CHANGES_REQUESTED** [review]
Hi Anmol,

Thanks for your efforts. I think several major issues need to be solved before being merged.

(1) In our GraphAug paper, the "discriminator model" implemented here is called "reward generation model", so I think you'd better avoid using "discriminator" in file names, class names, or python variable names. You may use "reward_gen" to replace "discriminator".

(2) It seems that here all configuration parameters are set to be constant in conf/discriminator_conf.py. It is better to make all configuration parameters tunable in the core package codes and save our used configuration parameters in the folder of example running codes (e.g., [https://github.com/divelab/DIG/tree/dig-stable/examples/ggraph/GraphDF/config](https://github.com/divelab/DIG/tree/dig-stable/examples/ggraph/GraphDF/config)).

(3) Current organization of auggraph branch is not easy for adding other graph augmentation baseline methods. I suggest to use the following organization (similar to the organization of most other branches in DIG).  
```bash
├── auggraph
│   ├── dataset
│   ├── method
│   │   ├── GraphAug
```
You may put the codes about dataset implements from your utils.py into auggraph/dataset folder, and put all implementations of GraphAug method into auggraph/method/GraphAug folder. When GraphAug codes are finalized, you can add other augmentation methods by creating a new folder under auggraph/method/ and putting codes there.

Best,
Youzhi Luo

**Review by lyzustc — CHANGES_REQUESTED** [review]
Hi Anmol,

Thanks for your efforts. Current codes and organizations look much better to me now. Two minor issues need to be solved before being merged.

(1) It is bettter to put the codes about dataset and data transformation implementations from dig/auggraph/method/GraphAug/utils.py to dig/auggraph/dataset/aug_dataset.py (as I have mentioned in point (3) of last comment). By doing this, we can make it convenient for other people to reuse our implemented data interface module in developing their own augmentation methods.

(2) Try to avoid using __init__.py under the folder examples/. Codes in this folder are not package codes but used to reproduce our results in papers or provide running examples for using DIG. Also, users will be instructed to run codes under the folder examples/. You may read some instruction README files uder the folder examples/ (e.g., [https://github.com/divelab/DIG/tree/dig-stable/examples/ggraph/GraphDF](https://github.com/divelab/DIG/tree/dig-stable/examples/ggraph/GraphDF)).

Best,
Youzhi Luo

**Comment by anmol-anand** [comment]
Hi Youzhi, i have addressed previous comments and added the generator code. The review is back with you. Thanks!

**Review by lyzustc — CHANGES_REQUESTED** [review]
Hi Anmol,

Thanks for your updates! Now I think the codes of GraphAug is almost done. Several issues need to be addressed before being merged.

(1) For running example codes in examples/auggraph folder, do not create another folder ''method'' but just create folders with method name and put all example codes of a method to their corresponding folders with method name. In other words, use the following structure:
```bash
├── examples/auggraph
│   ├── GraphAug
│   │   ├── conf
│   │   │   ├── generator_conf.py
│   │   │   ├── reward_gen_conf.py
│   │   ├── run_generator.py
│   │   ├── run_reward_gen.py
│   ├── new_method_name (add codes of a new method under this folder in the future)
```

(2) Do not use dig/auggraph/method/GraphAug/paths.py to make data set paths and model checkpoint saving paths fixed. We'd better make them an argument so users can specify these data paths when running codes. In running example codes under the examples/auggraph folder, use python argparse to let user specify these paths (can look at other examples codes for example like [https://github.com/divelab/DIG/blob/dig-stable/examples/ggraph/GraphDF/run_const_prop_opt.py](https://github.com/divelab/DIG/blob/dig-stable/examples/ggraph/GraphDF/run_const_prop_opt.py).

Best regards,
Youzhi Luo

**Comment by anmol-anand** [comment]
Hi Youzhi, thanks for the feedback. I have addressed these comments. The review is back with you.

**Review by lyzustc — COMMENTED** [review]
Hi Anmol,

Thanks for your hard work! Now all the codes look good to me. Please continue to work on codes for running graph classification with augmentations and let me know when they are done.

Best,
Youzhi Luo

**Comment by anmol-anand** [comment]
Hi Youzhi, 

I have added the code for augmented classification. Can you please have a look.

Thank you.
Anmol

**Review by lyzustc — COMMENTED** [review]
Hi Anmol,

Thanks for updating codes for running classification. These part of codes look good to me. Please continue to do the following jobs before finalizing GraphAug codes.

(1) In our experiments, we do not use the GINE model, though I have implemented it and passed the legacy codes to you. Please remove all codes related to the GINE model.

(2) Make sure all the running codes in examples/auggraph/GraphAug folder is bug-free. You may first install DIG codes from source, then follow other examples (e.g., [https://github.com/divelab/DIG/tree/dig-stable/examples/ggraph/GraphDF](https://github.com/divelab/DIG/tree/dig-stable/examples/ggraph/GraphDF)) to first enter the folder examples/auggraph/GraphAug folder in your terminal, then run the example codes.

Best regards,
Youzhi Luo

**Comment by anmol-anand** [comment]
Hi Youzhi, 

1. I have removed the code for GINE model.
2. Earlier the example python scripts were runnable from the root directory DIG, now they are runnable from examples/auggraph/GraphAug

The review is back with you.

**Review by lyzustc — APPROVED** [review]
Hi Anmol,

Thanks for your hard work! The GraphAug codes look good to me now. You can start working on the documentation now. Please follow the instructions in "Improving documentations" of the [contributing guideline](https://diveintographs.readthedocs.io/en/latest/contribution/instruction.html).

Best regards,
Youzhi Luo

**Comment by anmol-anand** [comment]
Hi Youzhi, I have added sphinx documentation for the auggraph module. Can you please review once.

**Review by lyzustc — CHANGES_REQUESTED** [review]
Hi Anmol,

Thanks for your hard work. The following modifications need to be done before merging the codes.

(1) The description in the class-level doc of DegreeTrans in dataset/aug_dataset.py is not appropriate. Change it to "This class is used to add vertex degree based node features to graphs. This is usually used to preprocess the graph datasets that do not have node features." Also, in the doc of its \_\_call__ function, change "Given sample graph" to "the graph with vertex degrees as node features".

(2) Avoid mentioning "label invariant augmentation" in the doc of AUG_trans in dataset/aug_dataset.py.  Also, in the doc of its \_\_call__, mention its returns as "a transformed graph".

(3) For the class-level doc of RunnerAugCls in method/GraphAug/runner_aug_cls.py, change "Runs a graph classification model" to "Runs the training of a...".  In the doc of its train_test function, change "run the training epochs" to "run the training". Do the similar changes to RunnerGenerator in method/GraphAug/runner_generator.py and RunnerRewardGen in method/GraphAug/runner_reward_gen.py.

Best regards,
Youzhi Luo

**Comment by anmol-anand** [comment]
Hi Youzhi, 
Thanks for the quick review. I have updated the documentation as you suggested.

**Review by lyzustc — APPROVED** [review]
Hi Anmol,

Thanks for your work. The doc looks good to me now.

Best regards,
Youzhi Luo

**Comment by anmol-anand** [comment]
Thanks for the review Youzhi!

**Pull request merged**
